---
- name: Update ubuntu servers
  hosts: ub1
  become: yes

  tasks:
  - name: Install apache2
    package:
      name: apache2
      state: present 

  - name: Start apache2
    service:
      name: apache2
      state: started

  - name: Enable apache2
    service:
      name: apache2
      enabled: yes

