---
- name: apache2 configuration file
  copy: src=apache2.conf dest=/etc/apache2/apache2.conf
  notify: restart apache service

- name: create the webpage index.html
  copy: src=index.html dest=/var/www/html/index.html

- name: copy the image resource
  copy: src=devops.png dest=/var/www/html/devops.png